### ISSUE TITLE
keep hitting torch.cuda.FloatTensor vs torch.FloatTensor in auto_tune

### ISSUE THREAD

**Issue by lessw2020** [eBay/AutoOpt#2]
Working on running  AutoOpt but I keep getting floatTensor vs cuda.FloatTensor mismatch when computing of the gradients starts. 
This seems to be that the model and data are on Cuda but the optimizer itself is not?  Not sure how to resolve.  Regular Adam, etc. works.
Here's the error:

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-14-ae954bf77c9f> in <module>
      1 for epoch in range(1, epochs + 1):
----> 2     train(epoch, model, train_loader, optimizer)
      3     test(model, test_loader)

<ipython-input-9-79f0cc3029c4> in train(epoch, model, train_loader, optimizer)
     18 
     19         loss.backward()
---> 20         optimizer.step()
     21 
     22         if batch_idx % 1000 == 0:

~/AutoOpt/auto_adam.py in step(self, closure, verbose)
    132                 hessian = denom / sqrt_bias_correction2
    133                 # print(torch.norm(hessian))
--> 134                 self.auto_tune(parameter=param, hessian=hessian, verbose=verbose)
    135                 group['lr'] = 1 - param.gamma[0]
    136                 adaptive_beta1 = param.gamma[1] / (1 - param.gamma[0])

~/AutoOpt/auto_optimizer.py in auto_tune(self, parameter, hessian, with_momentum, verbose)
    158         :param verbose: Be verbose and print computed values.
    159         """
--> 160         G = torch.stack((parameter.grad, parameter.grad - parameter.gradient_est))
    161         if hessian is None:
    162             B = G

RuntimeError: expected type torch.cuda.FloatTensor but got torch.FloatTensor

Thanks for  any assistance!
Less

**Comment by lessw2020** [comment]
Sorry, I figured out I had an erroneous model.cuda() call after making the optimizer.
Removing that, there is still a conflict but in reverse:

-------------------
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-15-ae954bf77c9f> in <module>
      1 for epoch in range(1, epochs + 1):
----> 2     train(epoch, model, train_loader, optimizer)
      3     test(model, test_loader)

<ipython-input-9-79f0cc3029c4> in train(epoch, model, train_loader, optimizer)
     18 
     19         loss.backward()
---> 20         optimizer.step()
     21 
     22         if batch_idx % 1000 == 0:

~/AutoOpt/auto_adam.py in step(self, closure, verbose)
    132                 hessian = denom / sqrt_bias_correction2
    133                 # print(torch.norm(hessian))
--> 134                 self.auto_tune(parameter=param, hessian=hessian, verbose=verbose)
    135                 group['lr'] = 1 - param.gamma[0]
    136                 adaptive_beta1 = param.gamma[1] / (1 - param.gamma[0])

~/AutoOpt/auto_optimizer.py in auto_tune(self, parameter, hessian, with_momentum, verbose)
    169         A[1][1] = torch.sum((B[1] * G[1])).item()
    170 
--> 171         self.compute_var(parameter=parameter, hessian=hessian)
    172         if verbose:
    173             print('N: ', self.N)

~/AutoOpt/auto_optimizer.py in compute_var(self, parameter, hessian)
    143                                 (self.N * (self.N - 1))
    144         else:
--> 145             parameter.var_est = torch.div(torch.pow(torch.add(parameter.grad_all, -parameter.grad), 2),
    146                                           hessian).sum().item() / (self.N * (self.N - 1))
    147 

RuntimeError: expected type torch.FloatTensor but got torch.cuda.FloatTensor

---------------------

**Comment by skopru** [comment]
Looking into it. Meanwhile, you can run the example on CPU instead of GPU.

**Comment by lessw2020** [comment]
Thanks a bunch Selçuk!  
I will run it on CPU for now and thanks again for checking into this :)

**Comment by lessw2020** [comment]
Hi Selçuk,
Possibly related but I can't train with it on the CPU, either with Auto_Adam nor regular Adam.  
It's just spinning it's wheels and is always at 10% or 9% (i.e. completely random).  Not sure if that is related to the params being stored elswhere but they don't seem to be being updated.

------------------------
Test set: Average loss: 0.3721, Accuracy: 980/10000 (9%)

Train Epoch: 11 [0/60000 (0%)]	Loss: 8.757422
Train Epoch: 11 [9000/60000 (15%)]	Loss: 7.236280
Train Epoch: 11 [18000/60000 (30%)]	Loss: 7.866436
Train Epoch: 11 [27000/60000 (45%)]	Loss: 10.472101
Train Epoch: 11 [36000/60000 (60%)]	Loss: 14.052526
Train Epoch: 11 [45000/60000 (75%)]	Loss: 12.578988
Train Epoch: 11 [54000/60000 (90%)]	Loss: 12.001129

Test set: Average loss: 0.3295, Accuracy: 982/10000 (9%)

Train Epoch: 12 [0/60000 (0%)]	Loss: 9.479150
Train Epoch: 12 [9000/60000 (15%)]	Loss: 12.103229
Train Epoch: 12 [18000/60000 (30%)]	Loss: 5.913055
Train Epoch: 12 [27000/60000 (45%)]	Loss: 11.299622
Train Epoch: 12 [36000/60000 (60%)]	Loss: 14.419320
Train Epoch: 12 [45000/60000 (75%)]	Loss: 16.773289
Train Epoch: 12 [54000/60000 (90%)]	Loss: 15.650626

Test set: Average loss: 0.4353, Accuracy: 974/10000 (9%)

---------------------------------------------------------------

**Comment by skopru** [comment]
Hi @lessw2020, commit d31b3fe should fix the GPU bug that you saw. The Adam optimizer problem is not related with this issue. So, I'll close the this one and move your comments regarding Adam/AutoAdam to a new issue.

**Comment by skopru** [comment]
@lessw2020, please reopen if this doesn't work for you.

**Comment by lessw2020** [comment]
Hi @skopru - that fix works great.  GPU  training is now up and running :)
Thanks for the fast fix and look forward to the other fix.
Have a good weekend!
